// Store configurations for SKU image scraping
// Expanded to 60+ stores with optimized HQ image extraction

export interface StoreConfig {
  name: string;
  baseUrl: string;
  searchUrlTemplate: string;
  selectors: {
    productLink: string;
    productImage: string;
    noResults: string;
    productFound: string;
    pagination?: string;
  };
  imageConfig: {
    highResAttribute: string;
    urlPatternFilter: RegExp;
    minWidth: number;
    minHeight: number;
  };
  headers?: Record<string, string>;
  rateLimit: number;
  notes: string;
  isActive: boolean;
}

export const storeConfigs: StoreConfig[] = [
  {
    name: "Harrods",
    baseUrl: "https://www.harrods.com",
    searchUrlTemplate: "https://www.harrods.com/en-gb/search?searchTerm={sku}",
    selectors: {
      productLink: "article a",
      productImage: "img[data-test-id=\"product-image-main\"]",
      noResults: "[data-test-id=\"no-results-found\"]",
      productFound: "h1[data-test-id=\"product-name\"]",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|sprite|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Very high-res (1200-2000px). Cloudinary CDN. JS rendering required.",
    isActive: true,
  },
  {
    name: "Nordstrom",
    baseUrl: "https://www.nordstrom.com",
    searchUrlTemplate: "https://www.nordstrom.com/sr?keyword={sku}",
    selectors: {
      productLink: "a[href*=\"/s/\"]",
      productImage: "div[id^=\"gallery-item-container-zoom-\"] img",
      noResults: "h1:contains(\"not found\")",
      productFound: "h1[itemprop=\"name\"]",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Excellent quality (1200-1600px). Scene7 CDN. Akamai protection.",
    isActive: true,
  },
  {
    name: "Selfridges",
    baseUrl: "https://www.selfridges.com/GB/en/",
    searchUrlTemplate: "https://www.selfridges.com/GB/en/cat/?freeText={sku}&srch=Y",
    selectors: {
      productLink: "a[data-testid='product_name_plp']",
      productImage: "div[data-testid='main-image'] img",
      noResults: "h2[data-testid='did-you-mean-title']",
      productFound: "h1[data-testid='pdp-product-title']",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder|filter/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Very high-res images. Cloudflare protection.",
    isActive: true,
  },
  {
    name: "Saks Fifth Avenue",
    baseUrl: "https://www.saksfifthavenue.com",
    searchUrlTemplate: "https://www.saksfifthavenue.com/search?q={sku}",
    selectors: {
      productLink: "a.product-tile-link",
      productImage: "img.saks-image",
      noResults: ".no-results-copy",
      productFound: ".product-detail > script[type=\"application/json\"]",
    },
    imageConfig: {
      highResAttribute: "src",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "High-res images available from Scene7 CDN. Protected by PerimeterX.",
    isActive: true,
  },
  {
    name: "Net-A-Porter",
    baseUrl: "https://www.net-a-porter.com",
    searchUrlTemplate: "https://www.net-a-porter.com/en-us/search?q={sku}",
    selectors: {
      productLink: "a.ProductItem24__link",
      productImage: "div.ImageCarousel8__imageContainer > img",
      noResults: "h2.SearchSorryMessage__heading",
      productFound: "h1.ProductInformation84__name",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb|sprite|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Ultra high-res (1500-2000px). Yoox CDN.",
    isActive: true,
  },
  {
    name: "Bergdorf Goodman",
    baseUrl: "https://www.bergdorfgoodman.com",
    searchUrlTemplate: "https://www.bergdorfgoodman.com/search.jsp?q={sku}",
    selectors: {
      productLink: "a.product-item-link",
      productImage: "img.product-image-primary",
      noResults: ".s-no-results",
      productFound: ".product-name",
    },
    imageConfig: {
      highResAttribute: "data-zoom-image",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Ultra high-res (1500-2000px). Scene7 CDN. Unable to access the website due to bot detection.",
    isActive: true,
  },
  {
    name: "Bloomingdale's",
    baseUrl: "https://www.bloomingdales.com",
    searchUrlTemplate: "https://www.bloomingdales.com/shop/search?keyword={sku}",
    selectors: {
      productLink: "a[data-auto=\"product-title-link\"]",
      productImage: "div.main-image-wrapper img",
      noResults: ".zero-results-header",
      productFound: "h1[data-auto=\"product-name\"]",
    },
    imageConfig: {
      highResAttribute: "src",
      urlPatternFilter: /logo|icon|banner|sprite|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "High-res images are available. The site uses Scene7 and Macy's CDN.",
    isActive: true,
  },
  {
    name: "Neiman Marcus",
    baseUrl: "https://www.neimanmarcus.com",
    searchUrlTemplate: "https://www.neimanmarcus.com/search.jsp?q={sku}",
    selectors: {
      productLink: ".product-template a",
      productImage: "#pdp-main-image",
      noResults: ".no-results-messaging",
      productFound: "h1[itemprop=name]",
    },
    imageConfig: {
      highResAttribute: "data-zoom-image",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder|swatch/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Very high-res images from Scene7 CDN. Access is restricted, selectors are best guesses.",
    isActive: true,
  },
  {
    name: "Fortnum & Mason",
    baseUrl: "https://www.fortnumandmason.com",
    searchUrlTemplate: "https://www.fortnumandmason.com/search?q={sku}",
    selectors: {
      productLink: "a.w-full.block",
      productImage: "img.w-full.object-cover",
      noResults: "[data-testid=\"no-results-found\"]",
      productFound: "h1[data-testid=\"product-title\"]",
    },
    imageConfig: {
      highResAttribute: "src",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "High-res images are available, but Cloudflare may block scraping.",
    isActive: true,
  },
  {
    name: "Luckyscent",
    baseUrl: "https://www.luckyscent.com",
    searchUrlTemplate: "https://www.luckyscent.com/search?q={sku}",
    selectors: {
      productLink: "a[href*='/products/']",
      productImage: "img.aspect-square.w-full",
      noResults: "h2.text-2xl.font-bold.tracking-tight.text-gray-900",
      productFound: "h1.product-title",
    },
    imageConfig: {
      highResAttribute: "src",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "High-resolution images are available.",
    isActive: true,
  },
  {
    name: "Twisted Lily",
    baseUrl: "https://www.twistedlily.com",
    searchUrlTemplate: "https://www.twistedlily.com/search?q={sku}",
    selectors: {
      productLink: "a.product-item__image-wrapper",
      productImage: "div.product-gallery--loaded img.rimage__image",
      noResults: ".boost-sd__search-result-empty",
      productFound: "h1.product-title",
    },
    imageConfig: {
      highResAttribute: "src",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "High-res (1000-1500px). Shopify CDN. Easy product JSON.",
    isActive: true,
  },
  {
    name: "Osswald NYC",
    baseUrl: "https://osswaldnyc.com",
    searchUrlTemplate: "https://osswaldnyc.com/search?q={sku}",
    selectors: {
      productLink: "a.product-item__image-link",
      productImage: "div.product-gallery--image img",
      noResults: ".template-search__empty",
      productFound: "h1.product-title",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Very high-res (1200-1800px). Shopify backend.",
    isActive: true,
  },
  {
    name: "Aedes de Venustas",
    baseUrl: "https://www.aedes.com",
    searchUrlTemplate: "https://www.aedes.com/search?q={sku}",
    selectors: {
      productLink: "a.grid-product__link",
      productImage: ".product__image-wrapper img",
      noResults: ".template-search__empty",
      productFound: "h1.product-single__title",
    },
    imageConfig: {
      highResAttribute: "data-src",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "High-res (1200-1500px). Standard Shopify.",
    isActive: true,
  },
  {
    name: "Beautyhabit",
    baseUrl: "https://www.beautyhabit.com",
    searchUrlTemplate: "https://www.beautyhabit.com/search?q={sku}",
    selectors: {
      productLink: "a.product-item-meta__title",
      productImage: "img.product-gallery__image",
      noResults: "h2.search__heading",
      productFound: "h1.product-meta__title",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "High-res images available in srcset attribute. Easy to scrape.",
    isActive: true,
  },
  {
    name: "Sephora",
    baseUrl: "https://www.sephora.com",
    searchUrlTemplate: "https://www.sephora.com/search?keyword={sku}",
    selectors: {
      productLink: "a[data-comp-name=\\\"ProductTile\\\"]",
      productImage: "button[data-comp-name=\\\"Carousel\\\"] img",
      noResults: "div[data-comp-name=\\\"EmptySearch\\\"]",
      productFound: "h1[data-comp-name=\\\"ProductName\\\"]",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "High-res images available in srcset. Heavy bot protection.",
    isActive: true,
  },
  {
    name: "Dillard's",
    baseUrl: "https://www.dillards.com",
    searchUrlTemplate: "https://www.dillards.com/search?q={sku}",
    selectors: {
      productLink: "a.product-link",
      productImage: ".product-detail-image-container img",
      noResults: ".page-title-container h1",
      productFound: "h1.product-name",
    },
    imageConfig: {
      highResAttribute: "data-zoom-image",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder|sprite/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality (800-1100px). Akamai CDN.",
    isActive: true,
  },
  {
    name: "John Lewis",
    baseUrl: "https://www.johnlewis.com",
    searchUrlTemplate: "https://www.johnlewis.com/search?search-term={sku}",
    selectors: {
      productLink: "a[data-test=\"product-card-title\"]",
      productImage: "div[data-test-id=\"pdp-image-gallery\"] img",
      noResults: "div[data-test-id=\"no-results-found\"]",
      productFound: "h1[data-test=\"product-title\"]",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality (900-1200px). Scene7 CDN.",
    isActive: true,
  },
  {
    name: "Fenwick",
    baseUrl: "https://www.fenwick.co.uk",
    searchUrlTemplate: "https://www.fenwick.co.uk/search?q={sku}",
    selectors: {
      productLink: "h3 > a",
      productImage: "div.product-media-gallery__item img",
      noResults: "div.search__empty-state",
      productFound: "h1.product-title",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|sprite|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images. Use srcset to get high-resolution images.",
    isActive: true,
  },
  {
    name: "Douglas",
    baseUrl: "https://www.douglas.de",
    searchUrlTemplate: "https://www.douglas.de/de/search?q={sku}",
    selectors: {
      productLink: "a.product-tile-minimal__link",
      productImage: ".pdp-stage__image-wrapper img",
      noResults: ".search-no-result-headline",
      productFound: ".pdp-headline",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality (800-1200px). Cloudflare. React SPA.",
    isActive: true,
  },
  {
    name: "Notino",
    baseUrl: "https://www.notino.co.uk",
    searchUrlTemplate: "https://www.notino.co.uk/search/?q={sku}",
    selectors: {
      productLink: "a.sc-jdHILj",
      productImage: "img#pd-image-main",
      noResults: "div.sc-bJTOcE",
      productFound: "h1[data-brand]",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images (800-1100px). The site is easy to scrape.",
    isActive: true,
  },
  {
    name: "Flaconi",
    baseUrl: "https://www.flaconi.de",
    searchUrlTemplate: "https://www.flaconi.de/search?q={sku}",
    selectors: {
      productLink: "a.product-card__image-wrapper",
      productImage: ".product-stage-main-image__container img",
      noResults: ".search-no-result__headline",
      productFound: "h1[itemprop='name']",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|sprite|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images. Cloudflare protected.",
    isActive: true,
  },
  {
    name: "Parfumdreams",
    baseUrl: "https://www.parfumdreams.de",
    searchUrlTemplate: "https://www.parfumdreams.de/search?q={sku}",
    selectors: {
      productLink: "a.product-card",
      productImage: ".product-image__container img",
      noResults: ".search-no-result",
      productFound: "h1.product-title",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images. Self-hosted CDN.",
    isActive: true,
  },
  {
    name: "The Perfume Shop",
    baseUrl: "https://www.theperfumeshop.com",
    searchUrlTemplate: "https://www.theperfumeshop.com/search?q={sku}",
    selectors: {
      productLink: "a.product-tile__name",
      productImage: "e2core-media[data-gallery-image-gallery-main] img",
      noResults: "div.no-results",
      productFound: "h1.pdp-title",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder|svg/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images (800-1100px). Cloudflare CDN.",
    isActive: true,
  },
  {
    name: "Escentual",
    baseUrl: "https://www.escentual.com",
    searchUrlTemplate: "https://www.escentual.com/search/?q={sku}",
    selectors: {
      productLink: "a.product-card-image-container",
      productImage: "div.product-single__photo-container img",
      noResults: "h2.search__no-results-heading",
      productFound: "h1.product-single__title",
    },
    imageConfig: {
      highResAttribute: "data-zoom-image",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images. Self-hosted.",
    isActive: true,
  },
  {
    name: "Feelunique",
    baseUrl: "https://www.feelunique.com",
    searchUrlTemplate: "https://www.feelunique.com/search?Search={sku}",
    selectors: {
      productLink: "a.product-card-link",
      productImage: "img.css-1rovmyu.e65zztl0",
      noResults: ".css-123n3g.e1622x3e3",
      productFound: "h1.css-11zrkxf.e65zztl0",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Feelunique is now part of Sephora. The website redirects to sephora.co.uk.",
    isActive: true,
  },
  {
    name: "Lookfantastic",
    baseUrl: "https://www.lookfantastic.com",
    searchUrlTemplate: "https://www.lookfantastic.com/elysium.search?search={sku}",
    selectors: {
      productLink: "a.product-listing__product-link",
      productImage: "div.product-image-gallery__main-image img",
      noResults: ".responsive-product-list-layout__message-container",
      productFound: "h1.product-name",
    },
    imageConfig: {
      highResAttribute: "src",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images (900-1200px). THG CDN.",
    isActive: true,
  },
  {
    name: "Cult Beauty",
    baseUrl: "https://www.cultbeauty.com",
    searchUrlTemplate: "https://www.cultbeauty.com/search/?q={sku}",
    selectors: {
      productLink: "a.product-card-name",
      productImage: "div[data-track=\"productImageScrolled\"] img",
      noResults: "h1",
      productFound: "#product-title",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images. THG platform.",
    isActive: true,
  },
  {
    name: "Sephora France",
    baseUrl: "https://www.sephora.fr",
    searchUrlTemplate: "https://www.sephora.fr/recherche?keyword={sku}",
    selectors: {
      productLink: "a.product-thumbnail",
      productImage: "img.product-image",
      noResults: ".no-results",
      productFound: "h1.product-name",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Unable to access the website due to a captcha. The provided selectors are based on common e-commerce",
    isActive: true,
  },
  {
    name: "Sephora Middle East",
    baseUrl: "https://www.sephora.ae",
    searchUrlTemplate: "https://www.sephora.ae/en/search?searchTerm={sku}",
    selectors: {
      productLink: "a.product-card",
      productImage: "div.product-image-container img",
      noResults: ".product-grid-container",
      productFound: "h1[class*='product-brand']",
    },
    imageConfig: {
      highResAttribute: "src",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality (900-1200px). Lighter protection.",
    isActive: true,
  },
  {
    name: "Sephora Spain",
    baseUrl: "https://www.sephora.es",
    searchUrlTemplate: "https://www.sephora.es/buscar?keyword={sku}",
    selectors: {
      productLink: "a.product-tile-link",
      productImage: "div.product-image-wrapper > button > picture > img",
      noResults: ".search-results-container.no-results",
      productFound: "h1.pdp-product__name",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder|avatar/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality (900-1200px). Akamai CDN.",
    isActive: true,
  },
  {
    name: "Sephora Italy",
    baseUrl: "https://www.sephora.it",
    searchUrlTemplate: "https://www.sephora.it/ricerca?keyword={sku}",
    selectors: {
      productLink: "a.product-thumb-link",
      productImage: "[data-test-id=\"pdpImage\"]",
      noResults: "div.error-page-content h2",
      productFound: "h1.title-1",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder|avatar/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images. The site uses a captcha on the search results page, so direct searches might be",
    isActive: true,
  },
  {
    name: "Faces (Wojooh)",
    baseUrl: "https://www.faces.ae",
    searchUrlTemplate: "https://www.faces.ae/en/search?q={sku}",
    selectors: {
      productLink: ".product-tile a",
      productImage: ".fotorama__stage__frame img",
      noResults: ".search-results-no-results",
      productFound: "h1.pdp-main__name",
    },
    imageConfig: {
      highResAttribute: "src",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images (800-1100px). Magento platform.",
    isActive: true,
  },
  {
    name: "Strawberrynet",
    baseUrl: "https://www.strawberrynet.com",
    searchUrlTemplate: "https://www.strawberrynet.com/en-us/search/?q={sku}",
    selectors: {
      productLink: ".mulltr-1ebp15j a",
      productImage: ".mulltr-j73erl img",
      noResults: ".mulltr-15g2f2e",
      productFound: "h1.mulltr-1jkae0c",
    },
    imageConfig: {
      highResAttribute: "src",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images. Self-hosted CDN.",
    isActive: true,
  },
  {
    name: "Tigerlily Perfumery",
    baseUrl: "https://www.tigerlilyperfumery.com",
    searchUrlTemplate: "https://www.tigerlilyperfumery.com/search?q={sku}",
    selectors: {
      productLink: "a.grid-product__link",
      productImage: "div.product-single__photo--flex-wrapper img",
      noResults: "#snize-search-results-grid-mode > .snize-search-results-header",
      productFound: ".product-single__title",
    },
    imageConfig: {
      highResAttribute: "data-srcset",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality (800-1100px). Shopify CDN.",
    isActive: true,
  },
  {
    name: "Indigo Perfumery",
    baseUrl: "https://www.indigoperfumery.com",
    searchUrlTemplate: "https://www.indigoperfumery.com/search?q={sku}",
    selectors: {
      productLink: ".grid-view-item__link",
      productImage: ".product-single__photo-wrapper img",
      noResults: "p.text-center",
      productFound: "h1.product-single__title",
    },
    imageConfig: {
      highResAttribute: "data-src",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images from Shopify CDN.",
    isActive: true,
  },
  {
    name: "Ajmal Perfumes",
    baseUrl: "https://shop.ajmalperfume.com",
    searchUrlTemplate: "https://shop.ajmalperfume.com/search?type=product&q={sku}",
    selectors: {
      productLink: ".product-item-info a",
      productImage: ".product.media img",
      noResults: ".search-results .empty",
      productFound: "div.product-info-main",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images (700-1000px). Shopify platform.",
    isActive: true,
  },
  {
    name: "El Corte Inglés",
    baseUrl: "https://www.elcorteingles.es",
    searchUrlTemplate: "https://www.elcorteingles.es/search/?term={sku}",
    selectors: {
      productLink: "a.product-card__title-link",
      productImage: "picture#_option_0 img",
      noResults: "div.search-feedback__title",
      productFound: "h1.product_detail-title",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images. The site is a bit slow and has some anti-scraping measures. The no-results sele",
    isActive: true,
  },
  {
    name: "Liberty London",
    baseUrl: "https://www.libertylondon.com",
    searchUrlTemplate: "https://www.libertylondon.com/uk/search?q={sku}",
    selectors: {
      productLink: "a.product-tile-image-container",
      productImage: "img.img-fluid",
      noResults: "h2.no-results-title",
      productFound: "h1.pdp-title",
    },
    imageConfig: {
      highResAttribute: "src",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality (800-1100px). Luxury UK retailer.",
    isActive: true,
  },
  {
    name: "Harvey Nichols",
    baseUrl: "https://www.harveynichols.com",
    searchUrlTemplate: "https://www.harveynichols.com/search/?q={sku}",
    selectors: {
      productLink: "a[data-e2e=\"product-card-name\"]",
      productImage: "img[data-e2e=\"pdp-image\"]",
      noResults: "div._3u064",
      productFound: "h1[data-e2e=\"pdp-product-name\"]",
    },
    imageConfig: {
      highResAttribute: "src",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images. Luxury retailer.",
    isActive: true,
  },
  {
    name: "SpaceNK",
    baseUrl: "https://www.spacenk.com",
    searchUrlTemplate: "https://www.spacenk.com/uk/search?q={sku}",
    selectors: {
      productLink: "a[data-testid='product-tile-link']",
      productImage: "img[data-testid='pdp-main-image']",
      noResults: "div[data-testid='no-search-results']",
      productFound: "h1[data-testid='pdp-product-name']",
    },
    imageConfig: {
      highResAttribute: "src",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images.",
    isActive: true,
  },
  {
    name: "Bluemercury",
    baseUrl: "https://bluemercury.com",
    searchUrlTemplate: "https://bluemercury.com/search?q={sku}",
    selectors: {
      productLink: "a.product-tile-link",
      productImage: ".product-media-image",
      noResults: ".search-results-empty-message",
      productFound: ".product-title h1",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images (800-1100px).",
    isActive: true,
  },
  {
    name: "Credo Beauty",
    baseUrl: "https://credobeauty.com",
    searchUrlTemplate: "https://credobeauty.com/search?q={sku}",
    selectors: {
      productLink: "a.card-information__text",
      productImage: "img.product-gallery__image",
      noResults: ".template-search__empty",
      productFound: "h1.product-meta__title",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images. Shopify platform.",
    isActive: true,
  },
  {
    name: "Cos Bar",
    baseUrl: "https://www.cosbar.com",
    searchUrlTemplate: "https://www.cosbar.com/search?q={sku}",
    selectors: {
      productLink: "a.product-item__title",
      productImage: "div.product-gallery__image img",
      noResults: "div.template-search__empty",
      productFound: "h1.product-single__title",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality (800-1100px). Luxury boutique.",
    isActive: true,
  },
  {
    name: "MiN New York",
    baseUrl: "https://min.com",
    searchUrlTemplate: "https://min.com/search?q={sku}",
    selectors: {
      productLink: "a.product-item__image-wrapper",
      productImage: "div.product-gallery__media img",
      noResults: ".template-search__empty",
      productFound: "h1.product-single__title",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images. The original website minnewyork.com is down, new website is min.com. The websit",
    isActive: true,
  },
  {
    name: "Scent Bar",
    baseUrl: "https://www.scentbar.com",
    searchUrlTemplate: "https://www.scentbar.com/search?q={sku}",
    selectors: {
      productLink: "a[href*='/products/']",
      productImage: "div[class*='product-gallery'] img",
      noResults: "div.template-search__empty",
      productFound: "h1",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "High-resolution images are available in the srcset attribute.",
    isActive: true,
  },
  {
    name: "The Fragrance Shop",
    baseUrl: "https://www.thefragranceshop.co.uk",
    searchUrlTemplate: "https://www.thefragranceshop.co.uk/search?q={sku}",
    selectors: {
      productLink: "a.css-1hplp2g",
      productImage: "img.css-1j67d3j",
      noResults: ".css-1g5k3v:empty",
      productFound: "h1.css-1pde252",
    },
    imageConfig: {
      highResAttribute: "src",
      urlPatternFilter: /logo|icon|banner|sprite|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images (800-1100px). Major UK retailer.",
    isActive: true,
  },
  {
    name: "Notino Spain",
    baseUrl: "https://www.notino.es",
    searchUrlTemplate: "https://www.notino.es/search/?q={sku}",
    selectors: {
      productLink: "a.sc-jTzLTM",
      productImage: "#pd-image-main",
      noResults: "div.sc-bYEvPH",
      productFound: "h1[data-product-code]",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality (800-1100px). Easy scraping.",
    isActive: true,
  },
  {
    name: "Notino Germany",
    baseUrl: "https://www.notino.de",
    searchUrlTemplate: "https://www.notino.de/search/?q={sku}",
    selectors: {
      productLink: "a[data-testid^=\"product-tile\"]",
      productImage: "#pd-image-main",
      noResults: "div.sc-bYEvPH.cZkZqS",
      productFound: "h1[data-testid=\"product-title\"]",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality (800-1100px). Easy scraping.",
    isActive: true,
  },
  {
    name: "Notino France",
    baseUrl: "https://www.notino.fr",
    searchUrlTemplate: "https://www.notino.fr/search/?q={sku}",
    selectors: {
      productLink: "a[data-testid=\"product-tile\"]",
      productImage: "img#pd-image-main",
      noResults: "div.sc-gTgzDb.kndQMT",
      productFound: "h1",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality (800-1100px). Minimal protection.",
    isActive: true,
  },
  {
    name: "Douglas Austria",
    baseUrl: "https://www.douglas.at",
    searchUrlTemplate: "https://www.douglas.at/de/search?q={sku}",
    selectors: {
      productLink: "a.product-tile-link",
      productImage: "img.product-image__media",
      noResults: ".rd__no-results",
      productFound: ".product-details",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality (800-1200px). Same as DE version. Had trouble with cookie banner, selectors are best gu",
    isActive: true,
  },
  {
    name: "Niche Beauty",
    baseUrl: "https://www.niche-beauty.com/en-us",
    searchUrlTemplate: "https://www.niche-beauty.com/en-us/search?q={sku}",
    selectors: {
      productLink: "a.product-item__link",
      productImage: "div.product-gallery__main-image-container img",
      noResults: "body.page-home",
      productFound: "h1.p-name",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images (800-1100px). Niche focus.",
    isActive: true,
  },
  {
    name: "Roullier White",
    baseUrl: "https://www.roullierwhite.com",
    searchUrlTemplate: "https://www.roullierwhite.com/search?q={sku}",
    selectors: {
      productLink: "a.card-wrapper",
      productImage: ".product__media img",
      noResults: "#shopify-section-template--21665319551303__main > p",
      productFound: "h1.product__title",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality images. Shopify store.",
    isActive: true,
  },
  {
    name: "FragranceNet",
    baseUrl: "https://www.fragrancenet.com",
    searchUrlTemplate: "https://www.fragrancenet.com/search/{sku}",
    selectors: {
      productLink: "div.result-list > div > a",
      productImage: "meta[property='og:image']",
      noResults: "div.no-results",
      productFound: "h1.heading",
    },
    imageConfig: {
      highResAttribute: "content",
      urlPatternFilter: /logo|icon|banner|thumb/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "Good quality. Uses og:image meta tag.",
    isActive: true,
  },
  {
    name: "Jomashop",
    baseUrl: "https://www.jomashop.com",
    searchUrlTemplate: "https://www.jomashop.com/search?q={sku}",
    selectors: {
      productLink: "a.product-card-link",
      productImage: "img#product-main-image-gallery",
      noResults: "div.search-empty-result",
      productFound: "h1.product-name",
    },
    imageConfig: {
      highResAttribute: "srcset",
      urlPatternFilter: /logo|icon|banner|thumb|placeholder/i,
      minWidth: 400,
      minHeight: 400,
    },
    rateLimit: 800,
    notes: "High-quality images available in srcset attribute.",
    isActive: true,
  },
];

// Helper functions
export function getActiveStores(): StoreConfig[] {
  return storeConfigs.filter((store) => store.isActive);
}

export function buildSearchUrl(store: StoreConfig, sku: string): string {
  return store.searchUrlTemplate.replace("{sku}", encodeURIComponent(sku));
}

export function isValidProductImage(url: string, store: StoreConfig): boolean {
  if (!url) return false;
  if (store.imageConfig.urlPatternFilter.test(url)) return false;
  return true;
}
